import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useStore } from '../store/index.js';
import styles from './Settings.module.css';
export function Settings({ onNavigate: _ }) {
    const { user, logout } = useStore();
    const [apiUrl, setApiUrl] = useState(import.meta.env['VITE_API_URL'] ?? 'http://localhost:3001/api/v1');
    return (_jsxs("div", { className: `${styles.container} scrollable`, children: [_jsx("h2", { className: styles.title, children: "Settings" }), _jsxs("div", { className: styles.section, children: [_jsx("h3", { className: styles.sectionTitle, children: "Account" }), _jsxs("div", { className: styles.userCard, children: [_jsx("div", { className: styles.avatar, children: user?.email?.[0]?.toUpperCase() ?? 'U' }), _jsxs("div", { className: styles.userInfo, children: [_jsx("span", { className: styles.userName, children: user?.name ?? user?.email }), _jsx("span", { className: styles.userEmail, children: user?.email }), _jsxs("span", { className: styles.userRole, children: [user?.role, " Plan"] })] })] }), _jsx("button", { className: styles.logoutBtn, onClick: logout, children: "Sign Out" })] }), _jsxs("div", { className: styles.section, children: [_jsx("h3", { className: styles.sectionTitle, children: "API Configuration" }), _jsxs("div", { className: styles.field, children: [_jsx("label", { children: "API Server URL" }), _jsx("input", { type: "text", value: apiUrl, onChange: (e) => setApiUrl(e.target.value), placeholder: "http://localhost:3001/api/v1" }), _jsx("span", { className: styles.fieldHint, children: "Change this to point to your ShortForge API server" })] })] }), _jsxs("div", { className: styles.section, children: [_jsx("h3", { className: styles.sectionTitle, children: "About" }), _jsxs("div", { className: styles.aboutInfo, children: [_jsxs("div", { className: styles.aboutRow, children: [_jsx("span", { children: "Version" }), _jsx("span", { children: "1.0.0" })] }), _jsxs("div", { className: styles.aboutRow, children: [_jsx("span", { children: "Plugin ID" }), _jsx("span", { children: "com.shortforge.ai" })] }), _jsxs("div", { className: styles.aboutRow, children: [_jsx("span", { children: "Supported" }), _jsx("span", { children: "Premiere Pro 23.0+" })] })] })] }), _jsxs("div", { className: styles.section, children: [_jsx("h3", { className: styles.sectionTitle, children: "Support" }), _jsxs("div", { className: styles.linkList, children: [_jsx("a", { href: "https://shortforge.ai/docs", target: "_blank", rel: "noreferrer", className: styles.link, children: "Documentation" }), _jsx("a", { href: "https://shortforge.ai/support", target: "_blank", rel: "noreferrer", className: styles.link, children: "Contact Support" }), _jsx("a", { href: "https://shortforge.ai/changelog", target: "_blank", rel: "noreferrer", className: styles.link, children: "Changelog" })] })] })] }));
}
